// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/determined.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName string            `protobuf:"bytes,1,opt,name=ClassName,proto3" json:"ClassName,omitempty"`
	Fields    map[string]*Value `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Struct) Reset() {
	*x = Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_determined_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_determined_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_proto_determined_proto_rawDescGZIP(), []int{0}
}

func (x *Struct) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The kind of value.
	//
	// Types that are assignable to Kind:
	//
	//	*Value_SingleStruct
	//	*Value_ListStruct
	//	*Value_MapStruct
	//	*Value_Map2Struct
	Kind isValue_Kind `protobuf_oneof:"kind"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_determined_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_determined_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_determined_proto_rawDescGZIP(), []int{1}
}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Value) GetSingleStruct() *Struct {
	if x, ok := x.GetKind().(*Value_SingleStruct); ok {
		return x.SingleStruct
	}
	return nil
}

func (x *Value) GetListStruct() *ListStruct {
	if x, ok := x.GetKind().(*Value_ListStruct); ok {
		return x.ListStruct
	}
	return nil
}

func (x *Value) GetMapStruct() *MapStruct {
	if x, ok := x.GetKind().(*Value_MapStruct); ok {
		return x.MapStruct
	}
	return nil
}

func (x *Value) GetMap2Struct() *Map2Struct {
	if x, ok := x.GetKind().(*Value_Map2Struct); ok {
		return x.Map2Struct
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_SingleStruct struct {
	SingleStruct *Struct `protobuf:"bytes,1,opt,name=single_struct,json=singleStruct,proto3,oneof"`
}

type Value_ListStruct struct {
	ListStruct *ListStruct `protobuf:"bytes,2,opt,name=list_struct,json=listStruct,proto3,oneof"`
}

type Value_MapStruct struct {
	MapStruct *MapStruct `protobuf:"bytes,3,opt,name=map_struct,json=mapStruct,proto3,oneof"`
}

type Value_Map2Struct struct {
	Map2Struct *Map2Struct `protobuf:"bytes,4,opt,name=map2_struct,json=map2Struct,proto3,oneof"`
}

func (*Value_SingleStruct) isValue_Kind() {}

func (*Value_ListStruct) isValue_Kind() {}

func (*Value_MapStruct) isValue_Kind() {}

func (*Value_Map2Struct) isValue_Kind() {}

type ListStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListFields []*Struct `protobuf:"bytes,1,rep,name=list_fields,json=listFields,proto3" json:"list_fields,omitempty"`
}

func (x *ListStruct) Reset() {
	*x = ListStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_determined_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStruct) ProtoMessage() {}

func (x *ListStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_determined_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStruct.ProtoReflect.Descriptor instead.
func (*ListStruct) Descriptor() ([]byte, []int) {
	return file_proto_determined_proto_rawDescGZIP(), []int{2}
}

func (x *ListStruct) GetListFields() []*Struct {
	if x != nil {
		return x.ListFields
	}
	return nil
}

type MapStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapFields map[string]*Struct `protobuf:"bytes,1,rep,name=map_fields,json=mapFields,proto3" json:"map_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapStruct) Reset() {
	*x = MapStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_determined_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStruct) ProtoMessage() {}

func (x *MapStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_determined_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStruct.ProtoReflect.Descriptor instead.
func (*MapStruct) Descriptor() ([]byte, []int) {
	return file_proto_determined_proto_rawDescGZIP(), []int{3}
}

func (x *MapStruct) GetMapFields() map[string]*Struct {
	if x != nil {
		return x.MapFields
	}
	return nil
}

type Map2Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map2Fields map[string]*MapStruct `protobuf:"bytes,1,rep,name=map2_fields,json=map2Fields,proto3" json:"map2_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Map2Struct) Reset() {
	*x = Map2Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_determined_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map2Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map2Struct) ProtoMessage() {}

func (x *Map2Struct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_determined_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map2Struct.ProtoReflect.Descriptor instead.
func (*Map2Struct) Descriptor() ([]byte, []int) {
	return file_proto_determined_proto_rawDescGZIP(), []int{4}
}

func (x *Map2Struct) GetMap2Fields() map[string]*MapStruct {
	if x != nil {
		return x.Map2Fields
	}
	return nil
}

var File_proto_determined_proto protoreflect.FileDescriptor

var file_proto_determined_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c,
	0x22, 0xa4, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x74, 0x68,
	0x63, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x48, 0x0a,
	0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe8, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x35, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63,
	0x6c, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12,
	0x32, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x4d, 0x61, 0x70,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x61, 0x70, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x32, 0x5f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63,
	0x6c, 0x2e, 0x4d, 0x61, 0x70, 0x32, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a,
	0x6d, 0x61, 0x70, 0x32, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x3d, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x12, 0x2f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x22, 0x9a, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12,
	0x3f, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x4d, 0x61, 0x70,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x1a, 0x4c, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa3,
	0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x70, 0x32, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x43, 0x0a,
	0x0b, 0x6d, 0x61, 0x70, 0x32, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e, 0x4d, 0x61, 0x70, 0x32,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x4d, 0x61, 0x70, 0x32, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6d, 0x61, 0x70, 0x32, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x1a, 0x50, 0x0a, 0x0f, 0x4d, 0x61, 0x70, 0x32, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x74, 0x68, 0x63, 0x6c, 0x2e,
	0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_determined_proto_rawDescOnce sync.Once
	file_proto_determined_proto_rawDescData = file_proto_determined_proto_rawDesc
)

func file_proto_determined_proto_rawDescGZIP() []byte {
	file_proto_determined_proto_rawDescOnce.Do(func() {
		file_proto_determined_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_determined_proto_rawDescData)
	})
	return file_proto_determined_proto_rawDescData
}

var file_proto_determined_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_determined_proto_goTypes = []interface{}{
	(*Struct)(nil),     // 0: dethcl.Struct
	(*Value)(nil),      // 1: dethcl.Value
	(*ListStruct)(nil), // 2: dethcl.ListStruct
	(*MapStruct)(nil),  // 3: dethcl.MapStruct
	(*Map2Struct)(nil), // 4: dethcl.Map2Struct
	nil,                // 5: dethcl.Struct.FieldsEntry
	nil,                // 6: dethcl.MapStruct.MapFieldsEntry
	nil,                // 7: dethcl.Map2Struct.Map2FieldsEntry
}
var file_proto_determined_proto_depIdxs = []int32{
	5,  // 0: dethcl.Struct.fields:type_name -> dethcl.Struct.FieldsEntry
	0,  // 1: dethcl.Value.single_struct:type_name -> dethcl.Struct
	2,  // 2: dethcl.Value.list_struct:type_name -> dethcl.ListStruct
	3,  // 3: dethcl.Value.map_struct:type_name -> dethcl.MapStruct
	4,  // 4: dethcl.Value.map2_struct:type_name -> dethcl.Map2Struct
	0,  // 5: dethcl.ListStruct.list_fields:type_name -> dethcl.Struct
	6,  // 6: dethcl.MapStruct.map_fields:type_name -> dethcl.MapStruct.MapFieldsEntry
	7,  // 7: dethcl.Map2Struct.map2_fields:type_name -> dethcl.Map2Struct.Map2FieldsEntry
	1,  // 8: dethcl.Struct.FieldsEntry.value:type_name -> dethcl.Value
	0,  // 9: dethcl.MapStruct.MapFieldsEntry.value:type_name -> dethcl.Struct
	3,  // 10: dethcl.Map2Struct.Map2FieldsEntry.value:type_name -> dethcl.MapStruct
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_determined_proto_init() }
func file_proto_determined_proto_init() {
	if File_proto_determined_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_determined_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_determined_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_determined_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_determined_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_determined_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Map2Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_determined_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Value_SingleStruct)(nil),
		(*Value_ListStruct)(nil),
		(*Value_MapStruct)(nil),
		(*Value_Map2Struct)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_determined_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_determined_proto_goTypes,
		DependencyIndexes: file_proto_determined_proto_depIdxs,
		MessageInfos:      file_proto_determined_proto_msgTypes,
	}.Build()
	File_proto_determined_proto = out.File
	file_proto_determined_proto_rawDesc = nil
	file_proto_determined_proto_goTypes = nil
	file_proto_determined_proto_depIdxs = nil
}
